language: c
cache:
  directories:
      - "$HOME/.cache"
      - "$HOME/.ccache"
before_install:
    - ccache -s
    - export PATH=/usr/lib/ccache:${PATH}
    - wget https://package-data.enthought.com/edm/rh5_x86_64/1.4/edm_1.4.1_linux_x86_64.sh && bash ./edm_1.4.1_linux_x86_64.sh -b -p $HOME
    - export PATH=${HOME}/edm/bin:${PATH}
    - edm environments create force -r requirements/edm_requirements.txt
    - . $HOME/.edm/envs/force/bin/activate 
install:
    - pip install -r requirements/requirements.txt
    - python setup.py develop
script:
    - pip install -r requirements/dev_requirements.txt
    - flake8 .
    - export ETS_TOOLKIT=qt4
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - python -m unittest discover
    - pip install -r requirements/doc_requirements.txt
    - sphinx-build -W doc/source doc/build/sphinx
