language: generic
cache:
  directories:
      - "$HOME/.cache"
      - "$HOME/.ccache"
dist: xenial
services:
    - xvfb
before_install:
    - ccache -s
    - export PATH=/usr/lib/ccache:${PATH}
    - wget https://package-data.enthought.com/edm/rh5_x86_64/1.9/edm_1.9.2_linux_x86_64.sh && bash ./edm_1.9.2_linux_x86_64.sh -b -f -p $HOME
    - export PATH=${HOME}/edm/bin:${PATH}
    - edm install -y --version 3.6 click setuptools
    - git clone git://github.com/force-h2020/force-bdss.git
    - pushd force-bdss && edm run -- python -m ci build-env && edm run -- python -m ci install && popd
    - sudo apt-get install --yes libglu1-mesa-dev mesa-common-dev
script:
    - edm run -- python -m ci install
    - edm run -- python -m ci flake8
    - export ETS_TOOLKIT=qt4
    - export DISPLAY=:99.0
    - edm run -- python -m ci test
    - edm run -- python -m ci docs
after_success:
    - edm run -- python -m ci coverage
    - bash <(curl -s https://codecov.io/bash)

